CREATE TABLE IF NOT EXISTS grupo6 ( 
	grupo6 int unsigned NOT NULL AUTO_INCREMENT,
	establecimiento int,
	telefono_establecimiento int,
	direccion_establecimiento varchar(40),
	nombre_establecimiento varchar(40),
	latitud float(6,6),
	longitud float (6,6),
	username_user_creador varchar(20),
	telefono_user_creador int,
	correo_user_creador varchar(50),
	password_user_creador varchar(30),
	nombre_user_creador varchar(30),
	tiponombre_user_creador int,
	nombre_dimension varchar(30),
	nombre_atributo varchar(20),
	descripcion_atributo varchar(40),
	nombre_servicio varchar(30),
	descripcion_servicio varchar(60),
	nombre_r_c varchar(40),
	servicio_trc int,
	establecimiento_trc int,
	valor_rc int,
	comentario_rc varchar(80),
	inicio_rc datetime,
	final_rc int,
	username_user_trc varchar(20),
	telefono_user_trc int,
	correo_user_trc varchar(20),
	password_user_trc varchar (30),
	nombre_user_trc varchar(20),
	nombre_tipousuariotrc varchar(30),
	PRIMARY KEY (grupo6)
);
